baseurl: /tufte-jekyll
title: kinomysli
subtitle: Content-centric blogging
author: Kamil
simple_search: http://google.com/search
description: A Jekyll theme for content-rich sites
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Europe/Warsaw
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: neovim
git:
  branch: master 
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/kinomysli.github.com/
